# class Genre < ActiveHash::Base
#   self.data = [
#     { id: 1, name: '---' },
#     { id: 2, name: 'メンズ' },
#     { id: 3, name: 'レディース' },
#     { id: 4, name: 'ベビー・キッズ' },
#     { id: 5, name: 'インテリア' },
#     { id: 6, name: '住まい' },
#     { id: 7, name: '小物' },
#     { id: 8, name: '本' },
#     { id: 9, name: '音楽' },
#     { id: 10, name: 'ゲーム' },
#     { id: 11, name: 'おもちゃ' },
#     { id: 12, name: 'ホビー' },
#     { id: 13, name: 'グッズ' },
#     { id: 13, name: '家電' },
#     { id: 13, name: 'スマホ' },
#     { id: 13, name: 'カメラ' },
#     { id: 13, name: 'スポーツ' },
#     { id: 13, name: 'レジャー' },
#     { id: 13, name: 'ハンドメイド' },
#     { id: 13, name: 'その他' },
#   ]
#   end

#     { id: 1, name: '---' },
#     { id: 2, name: '新品' },
#     { id: 3, name: '未使用' },
#     { id: 4, name: '未使用に近い' },
#     { id: 5, name: '目立った傷や汚れなし },
#     { id: 6, name: 'やや傷汚れあり' },
#     { id: 7, name: '傷や汚れあり' },
#     { id: 8, name: '全体的に状態が悪い' },

#     { id: 1, name: '---' },
#     { id: 2, name: '着払い（購入者負担）' },
#     { id: 3, name: '送料込み（出品者負担）' },
#     { id: 4, name: '未使用に近い' },
#     { id: 5, name: '目立った傷や汚れなし },
#     { id: 6, name: 'やや傷汚れあり' },
#     { id: 7, name: '傷や汚れあり' },
#     { id: 8, name: '全体的に状態が悪い' },

#     { id: 1, name: '---' },
#     { id: 2, name: '1\~2日発送' },
#     { id: 3, name: '2\~3日発送' },
#     { id: 4, name: '4\~7日発送' },
